server:
  port: 7777

eureka:
  instance:
    hostname: 172.19.36.109
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
