spring:
  application:
    name: api-gateway
server:
  port: 7776


eureka:
  client:
    service-url:
      defaultZone: http://172.19.36.109:7777/eureka/
  instance:  
        #发呆时间，即服务续约到期时间（缺省为90s）
        #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
        lease-expiration-duration-in-seconds: 9
        #表示eureka client发送心跳给server端的频率,默认为30 秒
        #如果在lease-expiration-duration-in-seconds后，server端没有收到client的心跳，则将摘除该instance
        #除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量
        lease-renewal-interval-in-seconds: 3
        #指定用ip访问而不是用主机名
        prefer-ip-address: true
        #指定真实的ip地址
        ip-address: ${spring.cloud.client.ipAddress}
        #指定在注册中心Status列显示的信息
        instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name} 


# 路由配置方式一  
zuul:  
  routes:  
    alen-test1-server: /test1/** #所有请求springboot-rest-template-feign的请求，都会被拦截，并且转发到service服务上  
  
  
# 路由配置方式二  
#zuul:  
#  routes:  
#    api-contract: # 其中api-contract是路由名称，可以随便定义，但是path和service-id需要一一对应  
#      path: /tools/** 
#      service-id: tqmsapp-resource-tools # springboot-feign为注册到Eureka上的服务名  






